# Harmony Jekyll theme general configurations
url: "https://stephantul.github.io"
baseurl: ""
title: "Stéphan Tulkens"
description: "NLP Person"

# Harmony theme configuration
harmony:
  name: Stéphan Tulkens
  description: NLP Person
  meta_description: "Stéphan Tulkens' Blog"
  basetheme: theme-base-01
  author:
    name: Stéphan Tulkens
    email: stephantul@gmail.com
    url: "https://stephantul.github.io"

  google_analytics_key:
  show_disclaimer: false

# Author (used by jekyll-seo-tag)
author:
  name: Stéphan Tulkens
  email: stephantul@gmail.com
  url: "https://stephantul.github.io"

lang: en

# Social identity (used for JSON-LD + OG)
social:
  name: "Stéphan Tulkens"
  links:
    - "https://github.com/stephantul"
    - "https://twitter.com/tulkenss"
    - "https://www.linkedin.com/in/stephantulkens/"
    - "https://scholar.google.com/citations?user=pvoqmHQAAAAJ"

# Twitter card metadata
twitter:
  username: tulkenss

# Conversion / Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
highlighter: rouge

# Permalinks
permalink: /blog/:title/

# Plugins (GitHub Pages safe)
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

whitelist:
  - jekyll-redirect-from

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: compressed
